export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';

export const INITIAL_EMPTY_ITEMS_BY_CATEGORY = 'INITIAL_EMPTY_ITEMS_BY_CATEGORY';
export const LOADING_ITEMS_BY_CATEGORY = 'LOADING_ITEMS_BY_CATEGORY';
export const SUCCESS_ITEMS_BY_CATEGORY = 'SUCCESS_ITEMS_BY_CATEGORY';
export const ERROR_ITEMS_BY_CATEGORY = 'ERROR_ITEMS_BY_CATEGORY';

export const REQUEST_ITEMS_BY_CATEGORY = 'REQUEST_ITEMS_BY_CATEGORY';
export const REQUEST_ITEMS_BY_CATEGORY_SUCCESS = 'REQUEST_ITEMS_BY_CATEGORY_SUCCESS';
export const REQUEST_ITEMS_BY_CATEGORY_ERROR = 'REQUEST_ITEMS_BY_CATEGORY_ERROR';

export const SAVE_DATA_SUCCESS = 'SAVE_DATA_SUCCESS';
export const SAVE_DATA_ERROR = 'SAVE_DATA_ERROR';
export const LOAD_CACHED_DATA_REQUEST = 'LOAD_CACHED_DATA_REQUEST';
export const LOAD_CACHED_DATA_SUCCESS = 'LOAD_CACHED_DATA_SUCCESS';
export const LOAD_CACHED_DATA_ERROR = 'LOAD_CACHED_DATA_ERROR';